Script started on Mon 20 Apr 2015 06:00:17 PM MDT
mintpaw@MintPaw-Lappy:~/cse113/lab10$ make clean.[K; make
rm *.o lab10
cc    -c -o binary.o binary.c
gcc -g -Wall lab10.c binary.o -o lab10
mintpaw@MintPaw-Lappy:~/cse113/lab10$ ./lab10 
Give word size: -1
Word size must be between 1 and 64 bits
Give word size: 65
Word size must be between 1 and 64 bits
Give word size: a
Word size must be between 1 and 64 bits
Give word size: 1
Unsigned [y/N]: y
Give expression: 1 + 1
Result:
1
+
1
-

0
decimal: 0
flags:
overflow: 1
carry: 1
sign: 0
parity: 1
zero: 1


Again? [Y/n]: 


Give word size: 3
Unsigned [y/N]: 
Give expression: 11 + 1
Result:
011
+
001
---

100
Compingsinged decimal: -5
flags:
overflow: 1
carry: 0
sign: 1
parity: 0
zero: 0


Again? [Y/n]: 


Give word size: 64
Unsigned [y/N]: 
Give expression: 42 - 3
Bad expression, error at char: 0
Give expression: 1101 + 2
Bad expression, error at char: 7
Give expression: 220   1001 ^ $ 3
Bad expression, error at char: 5
Give expression: ^[[A^[[B        101 % 1
Bad expression, error at char: 4
Give expression: 1111 + 1111111111111
Result:
0000000000000000000000000000000000000000000000000000000000001111
+
0000000000000000000000000000000000000000000000000001111111111111
----------------------------------------------------------------

0000000000000000000000000000000000000000000000000010000000001110
singed decimal: 8206
flags:
overflow: 0
carry: 0
sign: 0
parity: 1
zero: 0


Again? [Y/n]: 


Give word size: 3
Unsigned [y/N]: 
Give expression: 101 & 10 
Result:
101
&
001
---

001
singed decimal: 1
flags:
overflow: 0
carry: 0
sign: 0
parity: 0
zero: 0


Again? [Y/n]: 


Give word size: 2
Unsigned [y/N]: 
Give expression: 1 ^ 01
Result:
01
^
01
--

00
singed decimal: 0
flags:
overflow: 0
carry: 0
sign: 0
parity: 1
zero: 1


Again? [Y/n]: 


Give word size: 2
Unsigned [y/N]: 
Give expression: 10 ^ 91  01
Result:
10
^
01
--

11
Compingsinged decimal: -4
flags:
overflow: 0
carry: 0
sign: 1
parity: 1
zero: 0


Again? [Y/n]: n
mintpaw@MintPaw-Lappy:~/cse113/lab10$ exit
exit

Script done on Mon 20 Apr 2015 06:03:50 PM MDT
