Script started on Fri 10 Apr 2015 03:27:31 PM MDT
mintpaw@MintPaw-Lappy:~/cse113/lab9$ gcc -g -Wall lists.c -o lists
mintpaw@MintPaw-Lappy:~/cse113/lab9$ -[K/[K./lists 
First Node:
{ x: 2.000000, next: NULL } at: 0x8865008
Detailed list after inserts:
{ x: 1.000000, next: 0x8865028 } at: 0x8865018
{ x: 1.500000, next: 0x8865008 } at: 0x8865028
{ x: 2.000000, next: 0x8865038 } at: 0x8865008
{ x: 2.000000, next: NULL } at: 0x8865038
Detailed list after delete:
{ x: 1.000000, next: 0x8865008 } at: 0x8865018
{ x: 2.000000, next: 0x8865038 } at: 0x8865008
{ x: 2.000000, next: NULL } at: 0x8865038
mintpaw@MintPaw-Lappy:~/cse113/lab9$ vel[K[Kalgrind ./lists
==30774== Memcheck, a memory error detector
==30774== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==30774== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==30774== Command: ./lists
==30774== 
First Node:
{ x: 2.000000, next: NULL } at: 0x4206028
Detailed list after inserts:
{ x: 1.000000, next: 0x42060a8 } at: 0x4206068
{ x: 1.500000, next: 0x4206028 } at: 0x42060a8
{ x: 2.000000, next: 0x42060e8 } at: 0x4206028
{ x: 2.000000, next: NULL } at: 0x42060e8
Detailed list after delete:
{ x: 1.000000, next: 0x4206028 } at: 0x4206068
{ x: 2.000000, next: 0x42060e8 } at: 0x4206028
{ x: 2.000000, next: NULL } at: 0x42060e8
==30774== 
==30774== HEAP SUMMARY:
==30774==     in use at exit: 0 bytes in 0 blocks
==30774==   total heap usage: 4 allocs, 4 frees, 48 bytes allocated
==30774== 
==30774== All heap blocks were freed -- no leaks are possible
==30774== 
==30774== For counts of detected and suppressed errors, rerun with: -v
==30774== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
mintpaw@MintPaw-Lappy:~/cse113/lab9$ exit
exit

Script done on Fri 10 Apr 2015 03:27:56 PM MDT
