Script started on Wed 01 Apr 2015 02:58:19 PM MDT
mintpaw@MintPaw-Lappy:~/cse113/lab8$ valgrind ./dn[Kynamic
==28122== Memcheck, a memory error detector
==28122== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==28122== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==28122== Command: ./dynamic
==28122== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==28122== 
==28122== HEAP SUMMARY:
==28122==     in use at exit: 43 bytes in 1 blocks
==28122==   total heap usage: 1 allocs, 0 frees, 43 bytes allocated
==28122== 
==28122== LEAK SUMMARY:
==28122==    definitely lost: 43 bytes in 1 blocks
==28122==    indirectly lost: 0 bytes in 0 blocks
==28122==      possibly lost: 0 bytes in 0 blocks
==28122==    still reachable: 0 bytes in 0 blocks
==28122==         suppressed: 0 bytes in 0 blocks
==28122== Rerun with --leak-check=full to see details of leaked memory
==28122== 
==28122== For counts of detected and suppressed errors, rerun with: -v
==28122== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
mintpaw@MintPaw-Lappy:~/cse113/lab8$ exit
exit

Script done on Wed 01 Apr 2015 02:58:29 PM MDT
