Script started on Mon 30 Mar 2015 10:41:48 AM MDT
mintpaw@MintPaw-Lappy:~/cse113/lab8$ clear; gcc -g -Wall S[Kstring_error.c -o string_error.[K
[H[Jmintpaw@MintPaw-Lappy:~/cse113/lab8$ .[K./s[K[K[Kgdb [K[Kb si[Ktring
string_error  strings       
mintpaw@MintPaw-Lappy:~/cse113/lab8$ gdb string_error 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from string_error...done.
(gdb) r
Starting program: /home/mintpaw/cse113/lab8/string_error 
the original string:
c run, run c run

Program received signal SIGSEGV, Segmentation fault.
0x0804845f in main () at string_error.c:15
15                              *p = 'f'; /* change the value */
(gdb) bt
#0  0x0804845f in main () at string_error.c:15
(gdb) e
Ambiguous command "e": echo, edit, en, enable, end, eval, exec-file, explore.
(gdb) q
A debugging session is active.

	Inferior 1 [process 19936] will be killed.

Quit anyway? (y or n) y
mintpaw@MintPaw-Lappy:~/cse113/lab8$ 
[Kmintpaw@MintPaw-Lappy:~/cse113/lab8$ exit
exit

Script done on Mon 30 Mar 2015 10:42:49 AM MDT
