CC=gcc
CFLAGS=-g -Wall

all: fizzbuzz deg2rad anagram palindrome reverse

fizzbuzz: fizzbuzz.c
	$(CC) $(CFLAGS) $@.c -o $@


deg2rad: deg2rad.c
	$(CC) $(CFLAGS) $@.c -o $@

anagram: anagram.c
	$(CC) $(CFLAGS) $@.c -o $@

palindrome: palindrome.c
	$(CC) $(CFLAGS) $@.c -o $@

reverse: reverse.c
	$(CC) $(CFLAGS) $@.c -o $@

clean:
	rm fizzbuzz deg2rad anagram palindrome reverse
